server:
  port: 9999
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:oracle:thin:@localhost:1521:XE
    username: hr
    password: hr
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
#            ddl-auto: create
      #      ddl-auto: create-drop
#                          ddl-auto: update
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      enabled: true
      max-request-size: 40MB
      max-file-size: 40MB
      file-size-threshold: 100MB